# =====================================================================
#  PostgreSQL profile
#  Activate with:  --spring.profiles.active=postgres
#  Prerequisite:  CREATE DATABASE restapidb;   (and a user with rights)
# =====================================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/restapidb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
